// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ManageService(arg1) {
  return window['go']['main']['App']['ManageService'](arg1);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function ToggleLogging(arg1) {
  return window['go']['main']['App']['ToggleLogging'](arg1);
}
