// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ManageService(arg1:string):Promise<string>;

export function OpenLogFolder():Promise<void>;

export function ToggleLogging(arg1:boolean):Promise<string>;
